version: '3.8'

services:
  mongoDb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-Data:/data/db
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    command: python3 -m uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    depends_on:
      - mongoDb
volumes:
  mongo-Data:
